package de.kp.registry.server.neo4j.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import org.oasis.ebxml.registry.bindings.spi.CatalogObjectsRequest;
import org.oasis.ebxml.registry.bindings.spi.CatalogObjectsResponse;


/**
 * The Cataloger interface.
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Cataloger", targetNamespace = "urn:oasis:names:tc:ebxml-regrep:wsdl:spi:interfaces:4.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    org.oasis.ebxml.registry.bindings.rs.ObjectFactory.class,
    org.w3._1999.xlink.ObjectFactory.class,
    org.oasis.ebxml.registry.bindings.rim.ObjectFactory.class,
    org.oasis.ebxml.registry.bindings.query.ObjectFactory.class,
    org.oasis.ebxml.registry.bindings.lcm.ObjectFactory.class,
    org.oasis.ebxml.registry.bindings.spi.ObjectFactory.class
})

public interface Cataloger {

    /**
     * 
     * @param partCatalogObjectsRequest
     * @return
     *     returns org.oasis.ebxml.registry.bindings.spi.CatalogObjectsResponse
     * @throws MsgRegistryException
     */
	
    @WebMethod(action = "urn:oasis:names:tc:ebxml-regrep:wsdl:spi:bindings:4.0:Cataloger#catalogObjects")
    @WebResult(name = "CatalogObjectsResponse", targetNamespace = "urn:oasis:names:tc:ebxml-regrep:xsd:spi:4.0", partName = "partCatalogObjectsResponse")
    public CatalogObjectsResponse catalogObjects(
        @WebParam(name = "CatalogObjectsRequest", targetNamespace = "urn:oasis:names:tc:ebxml-regrep:xsd:spi:4.0", partName = "partCatalogObjectsRequest")
        CatalogObjectsRequest partCatalogObjectsRequest) throws MsgRegistryException;

}
