package de.kp.registry.server.neo4j.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import org.oasis.ebxml.registry.bindings.lcm.RemoveObjectsRequest;
import org.oasis.ebxml.registry.bindings.lcm.SubmitObjectsRequest;
import org.oasis.ebxml.registry.bindings.lcm.UpdateObjectsRequest;
import org.oasis.ebxml.registry.bindings.rs.RegistryResponseType;

/**
 * 
 *       The portType for LifecycleManager abstract interface.
 *     
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "LifecycleManager", targetNamespace = "urn:oasis:names:tc:ebxml-regrep:wsdl:registry:interfaces:4.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    org.oasis.ebxml.registry.bindings.rs.ObjectFactory.class,
    org.w3._1999.xlink.ObjectFactory.class,
    org.oasis.ebxml.registry.bindings.rim.ObjectFactory.class,
    org.oasis.ebxml.registry.bindings.query.ObjectFactory.class,
    org.oasis.ebxml.registry.bindings.lcm.ObjectFactory.class,
    org.oasis.ebxml.registry.bindings.spi.ObjectFactory.class
})

public interface LifecycleManager {

    /**
     * 
     * @param partRemoveObjectsRequest
     * @return
     *     returns org.oasis.ebxml.registry.bindings.rs.RegistryResponseType
     * @throws MsgRegistryException
     */
    @WebMethod(action = "urn:oasis:names:tc:ebxml-regrep:wsdl:registry:bindings:4.0:LifecycleManager#removeObjects")
    @WebResult(name = "RegistryResponse", targetNamespace = "urn:oasis:names:tc:ebxml-regrep:xsd:rs:4.0", partName = "partRegistryResponse")
    public RegistryResponseType removeObjects(
        @WebParam(name = "RemoveObjectsRequest", targetNamespace = "urn:oasis:names:tc:ebxml-regrep:xsd:lcm:4.0", partName = "partRemoveObjectsRequest")
        RemoveObjectsRequest partRemoveObjectsRequest) throws MsgRegistryException;

    /**
     * 
     * @param partSubmitObjectsRequest
     * @return
     *     returns org.oasis.ebxml.registry.bindings.rs.RegistryResponseType
     * @throws MsgRegistryException
     */
    @WebMethod(action = "urn:oasis:names:tc:ebxml-regrep:wsdl:registry:bindings:4.0:LifecycleManager#submitObjects")
    @WebResult(name = "RegistryResponse", targetNamespace = "urn:oasis:names:tc:ebxml-regrep:xsd:rs:4.0", partName = "partRegistryResponse")
    public RegistryResponseType submitObjects(
        @WebParam(name = "SubmitObjectsRequest", targetNamespace = "urn:oasis:names:tc:ebxml-regrep:xsd:lcm:4.0", partName = "partSubmitObjectsRequest")
        SubmitObjectsRequest partSubmitObjectsRequest) throws MsgRegistryException;

    /**
     * 
     * @param partUpdateObjectsRequest
     * @return
     *     returns org.oasis.ebxml.registry.bindings.rs.RegistryResponseType
     * @throws MsgRegistryException
     */
    @WebMethod(action = "urn:oasis:names:tc:ebxml-regrep:wsdl:registry:bindings:4.0:LifecycleManager#updateObjects")
    @WebResult(name = "RegistryResponse", targetNamespace = "urn:oasis:names:tc:ebxml-regrep:xsd:rs:4.0", partName = "partRegistryResponse")
    public RegistryResponseType updateObjects(
        @WebParam(name = "UpdateObjectsRequest", targetNamespace = "urn:oasis:names:tc:ebxml-regrep:xsd:lcm:4.0", partName = "partUpdateObjectsRequest")
        UpdateObjectsRequest partUpdateObjectsRequest) throws MsgRegistryException;

}
