package de.kp.registry.server.neo4j.service;

import javax.xml.ws.WebFault;

import org.oasis.ebxml.registry.bindings.rs.RegistryExceptionType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "RegistryException", targetNamespace = "urn:oasis:names:tc:ebxml-regrep:xsd:rs:4.0")
public class MsgRegistryException extends Exception {

	private static final long serialVersionUID = 4204168588717820241L;

	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private RegistryExceptionType faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public MsgRegistryException(String message, RegistryExceptionType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public MsgRegistryException(String message, RegistryExceptionType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: oasis.names.tc.ebxml_regrep.xsd.rs._4.RegistryExceptionType
     */
    public RegistryExceptionType getFaultInfo() {
        return faultInfo;
    }

}
