package de.kp.registry.server.neo4j.service;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import org.oasis.ebxml.registry.bindings.rim.NotificationType;

/**
 * PortType for a NotificationListener interface
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "NotificationListener", targetNamespace = "urn:oasis:names:tc:ebxml-regrep:wsdl:NotificationListener:interfaces:4.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    org.oasis.ebxml.registry.bindings.rs.ObjectFactory.class,
    org.w3._1999.xlink.ObjectFactory.class,
    org.oasis.ebxml.registry.bindings.rim.ObjectFactory.class,
    org.oasis.ebxml.registry.bindings.query.ObjectFactory.class,
    org.oasis.ebxml.registry.bindings.lcm.ObjectFactory.class,
    org.oasis.ebxml.registry.bindings.spi.ObjectFactory.class

})

public interface NotificationListener {

    /**
     * Delivers a Notification from registry to NotificationListener
     * 
     * @param notification
     */
	
    @WebMethod(action = "urn:oasis:names:tc:ebxml-regrep:wsdl:NotificationListener:bindings:4.0:NotificationListener:onNotification")
    @Oneway
    public void onNotification(
        @WebParam(name = "Notification", targetNamespace = "urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", partName = "Notification")
        NotificationType notification);

}
