package de.kp.registry.server.neo4j.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import org.oasis.ebxml.registry.bindings.query.QueryRequest;
import org.oasis.ebxml.registry.bindings.query.QueryResponse;
/**
 * 
 *       The portType for QueryManager abstract interface.
 *     
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "QueryManager", targetNamespace = "urn:oasis:names:tc:ebxml-regrep:wsdl:registry:interfaces:4.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    org.oasis.ebxml.registry.bindings.rs.ObjectFactory.class,
    org.w3._1999.xlink.ObjectFactory.class,
    org.oasis.ebxml.registry.bindings.rim.ObjectFactory.class,
    org.oasis.ebxml.registry.bindings.query.ObjectFactory.class,
    org.oasis.ebxml.registry.bindings.lcm.ObjectFactory.class,
    org.oasis.ebxml.registry.bindings.spi.ObjectFactory.class
})

public interface QueryManager {

    /**
     * 
     * @param partQueryRequest
     * @return
     *     returns org.oasis.ebxml.registry.bindings.query.QueryResponse.QueryResponse
     * @throws MsgRegistryException
     */
	
    @WebMethod(action = "urn:oasis:names:tc:ebxml-regrep:wsdl:registry:bindings:4.0:QueryManager#executeQuery")
    @WebResult(name = "QueryResponse", targetNamespace = "urn:oasis:names:tc:ebxml-regrep:xsd:query:4.0", partName = "partQueryResponse")
    public QueryResponse executeQuery(
        @WebParam(name = "QueryRequest", targetNamespace = "urn:oasis:names:tc:ebxml-regrep:xsd:query:4.0", partName = "partQueryRequest")
        QueryRequest partQueryRequest) throws MsgRegistryException;

}
