package de.kp.registry.server.neo4j.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import org.oasis.ebxml.registry.bindings.spi.ValidateObjectsRequest;
import org.oasis.ebxml.registry.bindings.spi.ValidateObjectsResponse;

/**
 * The Validator interface.
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Validator", targetNamespace = "urn:oasis:names:tc:ebxml-regrep:wsdl:spi:interfaces:4.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    org.oasis.ebxml.registry.bindings.rs.ObjectFactory.class,
    org.w3._1999.xlink.ObjectFactory.class,
    org.oasis.ebxml.registry.bindings.rim.ObjectFactory.class,
    org.oasis.ebxml.registry.bindings.query.ObjectFactory.class,
    org.oasis.ebxml.registry.bindings.lcm.ObjectFactory.class,
    org.oasis.ebxml.registry.bindings.spi.ObjectFactory.class
})

public interface Validator {

    /**
     * 
     * @param partValidateObjectsRequest
     * @return
     *     returns org.oasis.ebxml.registry.bindings.spi.ValidateObjectsResponse
     * @throws MsgRegistryException
     */
	
    @WebMethod(action = "urn:oasis:names:tc:ebxml-regrep:wsdl:spi:bindings:4.0:Validator#validateObjects")
    @WebResult(name = "ValidateObjectsResponse", targetNamespace = "urn:oasis:names:tc:ebxml-regrep:xsd:spi:4.0", partName = "partValidateObjectsResponse")
    public ValidateObjectsResponse validateObjects(
        @WebParam(name = "ValidateObjectsRequest", targetNamespace = "urn:oasis:names:tc:ebxml-regrep:xsd:spi:4.0", partName = "partValidateObjectsRequest")
        ValidateObjectsRequest partValidateObjectsRequest) throws MsgRegistryException;

}
